name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs: 
  prepare_simulator: 
    name: Prepare iOS Simulator
    runs-on: macOS-latest
    outputs:
      device_id: ${{ steps.simulator_device.outputs.iphone_id }}
    steps: 
    - name: Create iOS Simulator
      id: simulator_device
      run: |
        xcrun simctl list runtimes
        xcrun simctl list devicetypes
        echo creating device
        xcrun simctl create "iPhone 12 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro com.apple.CoreSimulator.SimRuntime.iOS-15-2
        echo "::set-output name=iphone_id::$(xcrun simctl create "iPhone 12 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro com.apple.CoreSimulator.SimRuntime.iOS-15-2)"
        xcrun simctl list devices
 
  build: 
    name: Build Project
    needs: prepare_simulator
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with: 
        xcode-version: 12.4
        
        
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme UIKIT-TMDB \
        -destination "platform=iOS Simulator,name=iPhone 12 Pro ,OS=15.2" \
        
  test: 
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with: 
          xcode-version: 12.4
      
      - name: Test
        run: |
          set -o pipefail
          xcodebuild test \
          -scheme UIKIT-TMDBTests \
          -destination "platform=iOS Simulator,name=iPhone 12 Pro ,OS=15.2" \
